[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2020-0056", # stdweb is unmaintained, but we don't care
]

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "BSD-2-Clause",
    "CC0-1.0",
    "BSL-1.0",
]
exceptions = [
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
    { name = "epaint", allow = ["OFL-1.1", "LicenseRef-UFL-1.0"] },
]
default = "deny"

[bans]
multiple-versions = "allow"
wildcards = "allow"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    #{ name = "foo", version = "0.5" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
